// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUwz3pGLyBr2C8labTwRLUcIK-SyiDnUw',
    appId: '1:208651859057:web:98d60713b397295d3217d0',
    messagingSenderId: '208651859057',
    projectId: 'fasum-app-b73b8',
    authDomain: 'fasum-app-b73b8.firebaseapp.com',
    storageBucket: 'fasum-app-b73b8.firebasestorage.app',
    measurementId: 'G-FZ6FYD0YYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCny5xyH_qOO6Logr6J__AajRFjRmN1moM',
    appId: '1:208651859057:android:292a333aec902ef63217d0',
    messagingSenderId: '208651859057',
    projectId: 'fasum-app-b73b8',
    storageBucket: 'fasum-app-b73b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmHQJZ4c5GSdhN1hCnhUgwYO64-FCx-6Q',
    appId: '1:208651859057:ios:b428114f70593e483217d0',
    messagingSenderId: '208651859057',
    projectId: 'fasum-app-b73b8',
    storageBucket: 'fasum-app-b73b8.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmHQJZ4c5GSdhN1hCnhUgwYO64-FCx-6Q',
    appId: '1:208651859057:ios:b428114f70593e483217d0',
    messagingSenderId: '208651859057',
    projectId: 'fasum-app-b73b8',
    storageBucket: 'fasum-app-b73b8.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUwz3pGLyBr2C8labTwRLUcIK-SyiDnUw',
    appId: '1:208651859057:web:87ba57aa4fb49c103217d0',
    messagingSenderId: '208651859057',
    projectId: 'fasum-app-b73b8',
    authDomain: 'fasum-app-b73b8.firebaseapp.com',
    storageBucket: 'fasum-app-b73b8.firebasestorage.app',
    measurementId: 'G-MWGB007R7D',
  );
}
