// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJWkfwc8xy7dhynYADANgAsiRDG48Vh44',
    appId: '1:105847169102:web:3cc45aae533f1cf248231f',
    messagingSenderId: '105847169102',
    projectId: 'first-app-c2366',
    authDomain: 'first-app-c2366.firebaseapp.com',
    databaseURL: 'https://first-app-c2366-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c2366.firebasestorage.app',
    measurementId: 'G-CP4R97EGZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvnvaj8n34A4Sj5tSIGCLztnDR_4GBenQ',
    appId: '1:105847169102:android:75180b91a81f13eb48231f',
    messagingSenderId: '105847169102',
    projectId: 'first-app-c2366',
    databaseURL: 'https://first-app-c2366-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c2366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq0Zv311iv4yuZXczcTUZsqZnTzme0eSo',
    appId: '1:105847169102:ios:a3742cf8cedca0d148231f',
    messagingSenderId: '105847169102',
    projectId: 'first-app-c2366',
    databaseURL: 'https://first-app-c2366-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c2366.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq0Zv311iv4yuZXczcTUZsqZnTzme0eSo',
    appId: '1:105847169102:ios:a3742cf8cedca0d148231f',
    messagingSenderId: '105847169102',
    projectId: 'first-app-c2366',
    databaseURL: 'https://first-app-c2366-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c2366.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJWkfwc8xy7dhynYADANgAsiRDG48Vh44',
    appId: '1:105847169102:web:693f4a1403c64d2c48231f',
    messagingSenderId: '105847169102',
    projectId: 'first-app-c2366',
    authDomain: 'first-app-c2366.firebaseapp.com',
    databaseURL: 'https://first-app-c2366-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-c2366.firebasestorage.app',
    measurementId: 'G-2TS32K64R0',
  );
}
